/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import connect.Account_Cnn;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class GeneralManagement extends javax.swing.JFrame {

    /**
     * Creates new form GeneralManagement
     */
//    private String dataLogin;
//    public QuanLyChung(String dataLogin) {
//        initComponents();
//        setLocationRelativeTo(null);
//        this.dataLogin = dataLogin;
//        this.setVisible(false);
//    }

    
    
    public GeneralManagement() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        order_btn = new javax.swing.JButton();
        menu_btn = new javax.swing.JButton();
        Thongke_btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        add_user = new javax.swing.JMenuItem();
        changePass = new javax.swing.JMenuItem();
        logOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý chung");
        setLocation(new java.awt.Point(500, 200));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/remote_50.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ CHUNG");

        order_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        order_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/order-food_50.png"))); // NOI18N
        order_btn.setText("Order");
        order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_btnActionPerformed(evt);
            }
        });

        menu_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menu_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu_50.png"))); // NOI18N
        menu_btn.setText("Menu");
        menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_btnActionPerformed(evt);
            }
        });

        Thongke_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Thongke_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/analysis_50.png"))); // NOI18N
        Thongke_btn.setText("Thống kê");
        Thongke_btn.setPreferredSize(new java.awt.Dimension(170, 60));
        Thongke_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thongke_btnActionPerformed(evt);
            }
        });

        jMenu1.setText("Tài khoản");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        add_user.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        add_user.setText("Thêm tài khoản");
        add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_userActionPerformed(evt);
            }
        });
        jMenu1.add(add_user);

        changePass.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        changePass.setText("Đổi mặt khẩu");
        changePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassActionPerformed(evt);
            }
        });
        jMenu1.add(changePass);

        logOut.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        logOut.setText("Đăng xuất");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jMenu1.add(logOut);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(order_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(menu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Thongke_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(order_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Thongke_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // NÚT ORDER
    private void order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        OrderManagement main_Order = new OrderManagement();
        main_Order.setVisible(true);
    }//GEN-LAST:event_order_btnActionPerformed
    
    // NÚT MENU
    private void menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuManagement main_menu = new MenuManagement();
        main_menu.setVisible(true);
    }//GEN-LAST:event_menu_btnActionPerformed
    
//    NÚT THỐNG KÊ
    private void Thongke_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thongke_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StatisticalManagement main_thongke = new StatisticalManagement(null);
        main_thongke.setVisible(true);
    }//GEN-LAST:event_Thongke_btnActionPerformed

    private void add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_userActionPerformed
        // TODO add your handling code here:
        if (!Account_Cnn.getInstance().getAccount().getUsername().equals("admin")){
            JOptionPane.showMessageDialog(null, "Bạn không có quyền truy cập chức năng này!");
            return;
        }
        AddAccount ttk = new AddAccount();
        ttk.setVisible(true);
        dispose();
    }//GEN-LAST:event_add_userActionPerformed

    private void changePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassActionPerformed
        // TODO add your handling code here:
        ChangePassword dmk = new ChangePassword();
        dmk.setVisible(true);
        dispose();
    }//GEN-LAST:event_changePassActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        this.setVisible(false);
     //   this.setVisible(false);
        dispose();
    }//GEN-LAST:event_logOutActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Thongke_btn;
    private javax.swing.JMenuItem add_user;
    private javax.swing.JMenuItem changePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JButton menu_btn;
    private javax.swing.JButton order_btn;
    // End of variables declaration//GEN-END:variables
}
